import type { SceneState } from '../model/state';

/**
 * One palette, two consumers.
 *
 * The DOM and the WebGL scene previously carried three separate copies of these
 * colours, which made "state — not identity — decides colour" a rule enforced by
 * discipline. This module is the single source: the stylesheet receives these
 * values as custom properties generated by `stateCssVariables()`, and the scene
 * reads the same object. A palette change cannot drift between them.
 *
 * Emissive values are NOT here — they are physically-meaningful HDR numbers that
 * only mean something to a renderer, and live beside the scene that uses them.
 */
export type StateColor = {
  /** Edge highlight / primary accent. */
  edge: string;
  /** Text and value colour on a dark ground. */
  label: string;
  /** Base of an illuminated surface. */
  surface: string;
  /** Static connection path. */
  connection: string;
};

export const stateColors: Record<SceneState, StateColor> = {
  neutral: { edge: '#233536', label: '#78827f', surface: '#081214', connection: '#0c3d3b' },
  healthy: { edge: '#4f9e94', label: '#42c8bd', surface: '#08211f', connection: '#0c5552' },
  active: { edge: '#43cec1', label: '#55cbbb', surface: '#092a28', connection: '#19867c' },
  attention: { edge: '#e0a100', label: '#d8a34d', surface: '#221b0d', connection: '#6d5320' },
  critical: { edge: '#d6342a', label: '#e16d5d', surface: '#150b09', connection: '#6d2b23' },
};

/**
 * Emitted into a `<style>` at the document root so CSS can use the same values
 * the scene does: `color: var(--state-critical-label)`.
 */
export function stateCssVariables(): string {
  const lines = Object.entries(stateColors).flatMap(([state, c]) => [
    `--state-${state}-edge:${c.edge}`,
    `--state-${state}-label:${c.label}`,
    `--state-${state}-surface:${c.surface}`,
    `--state-${state}-connection:${c.connection}`,
  ]);
  return `:root{${lines.join(';')}}`;
}
