import type { SceneState } from '@/lib/model/state';

/**
 * The state palette. The one thing allowed to decide colour.
 *
 * Two consumers, one definition: the stylesheet receives these as custom
 * properties generated by `toCssVariables()`, and the WebGL scene imports the
 * same object. A palette change cannot drift between them.
 *
 * Emissive values are deliberately NOT here — they are physically meaningful
 * HDR numbers that mean nothing outside a renderer, and live beside the scene
 * that uses them (`components/company-world/tokens/sceneStates.ts`).
 */
export type StateColor = {
  /** Edge highlight / primary accent. */
  edge: string;
  /** Text and value colour on a dark ground. */
  label: string;
  /** Base of an illuminated surface. */
  surface: string;
  /** Static connection path. */
  connection: string;
};

export const stateColors: Record<SceneState, StateColor> = {
  neutral: { edge: '#233536', label: '#78827f', surface: '#081214', connection: '#0c3d3b' },
  healthy: { edge: '#4f9e94', label: '#42c8bd', surface: '#08211f', connection: '#0c5552' },
  active: { edge: '#43cec1', label: '#55cbbb', surface: '#092a28', connection: '#19867c' },
  attention: { edge: '#e0a100', label: '#d8a34d', surface: '#221b0d', connection: '#6d5320' },
  critical: { edge: '#d6342a', label: '#e16d5d', surface: '#150b09', connection: '#6d2b23' },
};
