/**
 * Generates `components/company-world/generated/glyphIds.ts` from the kit manifest.
 *
 * The ten element ids were hand-maintained in seven places: ASSET_BUILDERS and
 * ASSET_INFO in the generator, manifest.json, the kit's own R3F wrapper, GLYPH_IDS
 * in the prototype's kit loader, the element sheet's ELEMENTS array, and the GLB
 * filenames themselves. The first two are the real source and already collapse into
 * the manifest; everything downstream was redundant and free to drift.
 *
 * Run: npm run emit:glyphs
 */
import { readFileSync, writeFileSync } from 'node:fs';

type Asset = {
  id: string;
  label: string;
  semantic: string;
  file: string;
  parts: number;
  triangles: number;
  vertices: number;
  bytes: number;
  materialNames: string[];
  dimensions: { x: number; y: number; z: number };
};

const manifest = JSON.parse(readFileSync('tools/glyph-kit/manifest.json', 'utf8')) as {
  assets: Asset[];
  materialNames: string[];
};

const q = (s: string) => `'${s.replace(/'/g, "\\'")}'`;

const entries = manifest.assets
  .map((a) => `  ${q(a.id)}: {
    label: ${q(a.label)},
    semantic: ${q(a.semantic)},
    parts: ${a.parts},
    triangles: ${a.triangles},
    bytes: ${a.bytes},
    dimensions: { x: ${a.dimensions.x}, y: ${a.dimensions.y}, z: ${a.dimensions.z} },
    materialNames: [${a.materialNames.map(q).join(', ')}],
  },`)
  .join('\n');

const out = `// GENERATED by scripts/emit-glyph-manifest.ts from tools/glyph-kit/manifest.json
// Do not edit. Run \`npm run emit:glyphs\` after regenerating the kit.

/** The canonical ten, in the kit's own order. */
export const GLYPH_IDS = [
${manifest.assets.map((a) => `  ${q(a.id)},`).join('\n')}
] as const;

export type GlyphId = (typeof GLYPH_IDS)[number];

/**
 * Every glTF material name the kit emits. \`MATERIAL_ROLES\` is declared
 * \`satisfies Record<KitMaterialName, MaterialRole>\`, so a material the kit adds
 * without a role becomes a compile error rather than a silent fallback.
 */
export const KIT_MATERIAL_NAMES = [
${manifest.materialNames.map((n) => `  ${q(n)},`).join('\n')}
] as const;

export type KitMaterialName = (typeof KIT_MATERIAL_NAMES)[number];

export type GlyphMeta = {
  label: string;
  semantic: string;
  parts: number;
  triangles: number;
  bytes: number;
  dimensions: { x: number; y: number; z: number };
  materialNames: readonly string[];
};

/** Measured facts about each asset, straight from the generator. */
export const GLYPH_MANIFEST = {
${entries}
} as const satisfies Record<GlyphId, GlyphMeta>;

/**
 * Where a glyph is served from.
 *
 * An absolute path into \`public/\`, not a bundler \`?url\` import: Vite treats
 * \`public/\` as copy-as-is and importing out of it is an anti-pattern. The cost is
 * no content hashing, so these do not get the immutable caching that
 * \`/_next/static/*\` gets in \`_headers\`. Acceptable while the GLBs are checksummed
 * artifacts that change rarely. This is the single indirection point, so moving
 * them into the bundled asset graph later is a change to one function.
 */
export function glyphUrl(id: GlyphId): string {
  return \`/models/innerflect-v1/\${id}.glb\`;
}
`;

writeFileSync('components/company-world/generated/glyphIds.ts', out);
console.log(`emitted ${manifest.assets.length} glyphs, ${manifest.materialNames.length} material names`);
